env:
  - gitlab_user=root gitlab_password=5iveL!fe gitlab_host=http://localhost:8080
services:
  - redis-server
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
rvm:
  - 2.1.0
# install local gitlab
before_install:
  - scripts/prepare_test_env.sh
  - scripts/install_gitlab.sh
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script: coverage run --source=gitlab setup.py test
after_success:
  coveralls