#env:
#  global:
#  - secure: LLkxKuTpD5D4k8x8qCXKGdwLpQvlVZ0AuC0TOYTPcZfm0VJE/Ppg+XgikiIdlD5f2+u/fBfn6FwMfdcnawGrNCJjNtLuQ9Dp4vTvqBfgsUhmkPAkV1nbKajYSgyAvFxKyhYhQlLra3gV6pplIFtKg7KZmtwnN5BqWmvA4m3rd9U=
#  - secure: bpXQdUjLAAF+IQLgsZPGA8Dy5YgbJvRW4QO0zEzLmFTl7/Cr5OsKHFEWtBoGlziP+l+A+iDLTDYsX6gF6d9WFv1SItnMEWwNzWG7ef4sQ4VSoK9vdJ9bon/a+mU3Za1rZ1hd9PjJBuhj6QY4pmIQiMebcuYP0ekg6zsn3RNSO1Q=
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# install local gitlab
before_install:
  - scripts/prepare_test_ev.sh
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script: coverage run --source=gitlab setup.py test
after_success:
  coveralls